"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Application.py']
DATA_FILES = [('images', ['images/logo-bokmerk.png', 'images/legend.png'])]
OPTIONS = {
    'iconfile': 'images/icon.png'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
