"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
sys.setrecursionlimit(5000)

from setuptools import setup

APP = ['Bokmerk.py']
DATA_FILES = [
    ('images', ['images/logo-bokmerk.png', 'images/legend.png']),
]

OPTIONS = {
    'iconfile': 'images/icon.png',
    'optimize': 2,
    'packages': [
        'PIL',
        'tkinter',
        'fpdf',
        'pdfminer',
        'charset_normalizer',
        'cffi',
    ],
    'excludes': ['pypdfium2_raw'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
